imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:      %database_driver%
                host:        %database_host%
                port:        %database_port%
                dbname:      %database_name%
                user:        %database_user%
                password:    %database_password%
                unix_socket: %database_socket%
                charset:     UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        proxy_namespace: Proxies
        proxy_dir: "%kernel.cache_dir%/doctrine/orm/Proxies"
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
                connection: default

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
